name: simplified_bloc
description: A package to simplify BLoC state management.
version: 1.0.6
homepage: https://github.com/shazawdidi/simplified_bloc
repository: https://github.com/shazawdidi/simplified_bloc
issue_tracker: https://github.com/shazawdidi/simplified_bloc/issues
environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0  # Update this to the latest stable version available

dev_dependencies:
  flutter_test:
    sdk: flutter  # Add the testing framework for Flutter
